const LocalizationKeys = {
    USER_CREATED: 'USER_CREATED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_REQUEST: 'INVALID_REQUEST',
    GENERAL_ERROR: 'GENERAL_ERROR',
    INVALID_EMAIL: 'INVALID_EMAIL',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    DATABASE_OCCURRED: 'DATABASE_OCCURRED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    USER_EXISTS: 'USER_EXISTS',           
    DATABASE_ERROR: 'DATABASE_ERROR',     
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR'

};

module.exports = LocalizationKeys;
