const LocalizationKeys = {
    USER_CREATED: 'USER_CREATED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_REQUEST: 'INVALID_REQUEST',
    GENERAL_ERROR: 'GENERAL_ERROR',
    INVALID_EMAIL: 'INVALID_EMAIL',
    WEAK_PASSWORD: 'WEAK_PASSWORD'
};

module.exports = LocalizationKeys;
